### ISSUE TITLE
some woff2 files are corrupted in the latest version

### ISSUE THREAD

**Issue by pschiffe** [GreatWizard/notosans-fontface#8]
Hello,

some woff2 files in this repository are corrupted and it's not possible to use them in firefox or chrome. In firefox the error message is that the sanitizer failed for the font or something like that.

For example the corrupted file is https://github.com/GreatWizard/notosans-fontface/blob/master/fonts/NotoSans-Regular.woff2 and you can also check it on this page: https://www.fontsquirrel.com/tools/webfont-generator (try to upload the file there, it will say `The font 'notosans-regular.woff2' is corrupt and cannot be converted.`

The corrupted files are in version 1.2.1; version 1.1.0 is working fine for me.

peter

**Comment by GreatWizard** [comment]
Thaks for your feedbacks. i'm investigating

**Comment by GreatWizard** [comment]
v1.2.2 is released with the fix about woff2

**Comment by pschiffe** [comment]
Hey @GreatWizard , I've tried to upgrade to 1.2.2, but the files are still corrupted :(
```
downloadable font: rejected by sanitizer (font-family: "Noto Sans" style:normal weight:400 stretch:100 src index:3)
downloadable font: rejected by sanitizer (font-family: "Noto Sans" style:normal weight:700 stretch:100 src index:3)
```

Also when I try https://github.com/GreatWizard/notosans-fontface/blob/master/fonts/NotoSans-Regular.woff2 in https://www.fontsquirrel.com/tools/webfont-generator it still says the same thing - `The font 'notosans-regular.woff2' is corrupt and cannot be converted.`

peter
